WITH VAL_RECORDS AS
(
SELECT  MRE.EXTN_ATTRIBUTE_CHAR001  VAL_DOCNO_3PL
FROM   MKT_REF_ENTITIES MRE
,      WSH_DELIVERY_DETAILS wdd 
,      WSH_DELIVERY_ASSIGNMENTS wda 
,      WSH_NEW_DELIVERIES wnd 
,      INV_ORGANIZATION_DEFINITIONS_V   IODV 
WHERE  MRE.ATTRIBUTE_CATEGORY = 'KOR_UPS_DOC_c'
AND    MRE.EXTN_ATTRIBUTE_CHAR004 = 'OrderCreationRequest'
AND    WDD.ORGANIZATION_ID  = IODV.ORGANIZATION_ID 
AND    TO_CHAR ( WDD.DELIVERY_DETAIL_ID)  =  SUBSTR (  EXTN_ATTRIBUTE_CHAR001  , 1, INSTR ( EXTN_ATTRIBUTE_CHAR001 , '-' ) - 1)
AND    WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID 
AND    WDA.DELIVERY_ID = WND.DELIVERY_ID 
AND    WND.STATUS_CODE  = 'CL'
---------
AND    MRE.CREATION_DATE   BETWEEN     :FROM_SEND_DATE  AND  :TO_SEND_DATE
AND    MRE.EXTN_ATTRIBUTE_CHAR001 =   WND.DELIVERY_NAME
GROUP BY  MRE.EXTN_ATTRIBUTE_CHAR001
)

,    SEC_BU AS 
(
SELECT  BU.BU_ID                 SEC_BU_ID
FROM FUN_ALL_BUSINESS_UNITS_V bu
WHERE 1 = 1
AND EXISTS  ( SELECT 1  
              FROM fusion.FUN_USER_ROLE_DATA_ASGNMNTS ROLE
              ,    fusion.per_users pu
              ,    fusion.per_roles_dn_vl pr
              WHERE 1 = 1
              AND  role.org_id       = bu.bu_id
			  AND pu.USER_GUID = role.USER_GUID
			  AND pr.ROLE_COMMON_NAME = role.ROLE_NAME
			  AND pu.USER_GUID = FND_GLOBAL.USER_GUID
)
)

,        QRY AS 
(
SELECT 'SO'  GRP,
MRE.EXTN_ATTRIBUTE_CHAR007 MESSAGEIDENTIFIER
,MRE.EXTN_ATTRIBUTE_CHAR001  DOCNO_3PL,
MRE.CREATION_DATE SEND_DATE,
MRE.ID  HEADER_ID
, MRE.EXTN_ATTRIBUTE_CHAR012 SERVICETYPE,
MRE.EXTN_ATTRIBUTE_CHAR068 ServiceLevel,
MRE.EXTN_ATTRIBUTE_CHAR069 ModeOfTransport,
MRE.EXTN_ATTRIBUTE_CHAR014 carrier,
IODV.BUSINESS_UNIT_NAME
, WDD.DELIVERY_DETAIL_ID   QRY_DELIVERY_DETAIL_ID
,   DHA.ORDER_NUMBER 
,   DFLA.ORG_ID   DFLA_ORG_ID 
, FABUV.BU_NAME 
FROM  MKT_REF_ENTITIES MRE
,     WSH_DELIVERY_DETAILS wdd 
,      DOO_FULFILL_LINES_ALL                  DFLA
,      DOO_HEADERS_ALL                        DHA 
,     FUN_ALL_BUSINESS_UNITS_V fabuv 
,     INV_ORGANIZATION_DEFINITIONS_V   IODV 
,     SEC_BU              SEC_BU
WHERE  MRE.ATTRIBUTE_CATEGORY = 'KOR_UPS_DOC_c'
AND   MRE.EXTN_ATTRIBUTE_CHAR004 = 'OrderCreationRequest'
AND   WDD.ORGANIZATION_ID  = IODV.ORGANIZATION_ID 
AND    DFLA.ORG_ID  = fabuv.BU_ID (+)
--AND    WDD.DELIVERY_DETAIL_ID  = 1175042
AND    WDD.SOURCE_SHIPMENT_ID             = DFLA.FULFILL_LINE_ID (+)
AND    DFLA.HEADER_ID                     = DHA.HEADER_ID  (+)
AND  TO_CHAR ( WDD.DELIVERY_DETAIL_ID)  =  SUBSTR (  EXTN_ATTRIBUTE_CHAR001  , 1, INSTR ( EXTN_ATTRIBUTE_CHAR001 , '-' ) - 1)

AND   MRE.CREATION_DATE   BETWEEN     :FROM_SEND_DATE  AND  :TO_SEND_DATE
AND   DFLA.ORG_ID   = SEC_BU.SEC_BU_ID
AND     (  FABUV.BU_NAME  IN ( :P_BU_NAME )  OR 'ALL' IN ( :P_BU_NAME || 'ALL'))
AND  EXISTS (   SELECT 1 
                FROM VAL_RECORDS
                WHERE 1 = 1
                AND  MRE.EXTN_ATTRIBUTE_CHAR001  =  VAL_RECORDS.VAL_DOCNO_3PL
                )
)

,   LINES_DET AS 
(
SELECT EXTN_ATTRIBUTE_CHAR014   SHIPMENT_LINE_ID,
       EXTN_ATTRIBUTE_CHAR007   ITEM,
       SHIPMENTLINES.ID,
       EXTN_ATTRIBUTE_NUMBER001 SHIPMENT_ID,
       EXTN_ATTRIBUTE_CHAR008   REQUESTEDQUANTITY,
       EXTN_ATTRIBUTE_NUMBER003 DELIVERY_DETAIL_ID, 
       wdd.RELEASED_STATUS     RELEASED_STATUS_code , 
       flvv.MEANING            RELEASED_STATUS_MEANING
  FROM MOT_REF_ENTITIES SHIPMENTLINES
  ,    WSH_DELIVERY_DETAILS wdd   
  ,    FND_LOOKUP_VALUES_VL flvv 
 WHERE  1 = 1 
 AND   wdd.RELEASED_STATUS   = flvv.LOOKUP_CODE (+) 
 AND   flvv.LOOKUP_TYPE  (+) =   'WSH_PICK_STATUS'
 --AND   wdd.RELEASED_STATUS  = 'R'
 AND   SHIPMENTLINES.ATTRIBUTE_CATEGORY = 'KOR_UPS_TRANS_c'
 AND   EXTN_ATTRIBUTE_CHAR014  = to_char (  wdd.DELIVERY_DETAIL_ID   ) 
)



SELECT *
FROM QRY
,    LINES_DET   LINES_DET
WHERE 1 = 1
AND    TO_CHAR ( QRY.HEADER_ID )  = LINES_DET.SHIPMENT_ID --(+)